<?php

/**
 * BaseFlag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property text $description
 * @property string $color
 * @property string $cssClass
 * @property integer $weight
 * @property Doctrine_Collection $Keyword
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method text                getDescription() Returns the current record's "description" value
 * @method string              getColor()       Returns the current record's "color" value
 * @method string              getCssClass()    Returns the current record's "cssClass" value
 * @method integer             getWeight()      Returns the current record's "weight" value
 * @method Doctrine_Collection getKeyword()     Returns the current record's "Keyword" collection
 * @method Flag                setId()          Sets the current record's "id" value
 * @method Flag                setName()        Sets the current record's "name" value
 * @method Flag                setDescription() Sets the current record's "description" value
 * @method Flag                setColor()       Sets the current record's "color" value
 * @method Flag                setCssClass()    Sets the current record's "cssClass" value
 * @method Flag                setWeight()      Sets the current record's "weight" value
 * @method Flag                setKeyword()     Sets the current record's "Keyword" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFlag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flag');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('color', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('cssClass', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Keyword', array(
             'local' => 'id',
             'foreign' => 'flag_id'));
    }
}