<?php

/**
 * BaseEmailOutgoing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $email_id
 * @property string $recipient_email
 * @property Email $Email
 * 
 * @method integer       getId()              Returns the current record's "id" value
 * @method integer       getEmailId()         Returns the current record's "email_id" value
 * @method string        getRecipientEmail()  Returns the current record's "recipient_email" value
 * @method Email         getEmail()           Returns the current record's "Email" value
 * @method EmailOutgoing setId()              Sets the current record's "id" value
 * @method EmailOutgoing setEmailId()         Sets the current record's "email_id" value
 * @method EmailOutgoing setRecipientEmail()  Sets the current record's "recipient_email" value
 * @method EmailOutgoing setEmail()           Sets the current record's "Email" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmailOutgoing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email_outgoing');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('recipient_email', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Email', array(
             'local' => 'email_id',
             'foreign' => 'id'));
    }
}