<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email_address
 * @property string $first_name
 * @property string $last_name
 * @property string $phone_number
 * @property boolean $is_approved
 * @property Doctrine_Collection $Inmate
 * @property Doctrine_Collection $InmateContact
 * @property Doctrine_Collection $Email
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getEmailAddress()  Returns the current record's "email_address" value
 * @method string              getFirstName()     Returns the current record's "first_name" value
 * @method string              getLastName()      Returns the current record's "last_name" value
 * @method string              getPhoneNumber()   Returns the current record's "phone_number" value
 * @method boolean             getIsApproved()    Returns the current record's "is_approved" value
 * @method Doctrine_Collection getInmate()        Returns the current record's "Inmate" collection
 * @method Doctrine_Collection getInmateContact() Returns the current record's "InmateContact" collection
 * @method Doctrine_Collection getEmail()         Returns the current record's "Email" collection
 * @method Contact             setId()            Sets the current record's "id" value
 * @method Contact             setEmailAddress()  Sets the current record's "email_address" value
 * @method Contact             setFirstName()     Sets the current record's "first_name" value
 * @method Contact             setLastName()      Sets the current record's "last_name" value
 * @method Contact             setPhoneNumber()   Sets the current record's "phone_number" value
 * @method Contact             setIsApproved()    Sets the current record's "is_approved" value
 * @method Contact             setInmate()        Sets the current record's "Inmate" collection
 * @method Contact             setInmateContact() Sets the current record's "InmateContact" collection
 * @method Contact             setEmail()         Sets the current record's "Email" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email_address', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('first_name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('last_name', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('phone_number', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Inmate', array(
             'refClass' => 'InmateContact',
             'local' => 'inmate_id',
             'foreign' => 'contact_id'));

        $this->hasMany('InmateContact', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $this->hasMany('Email', array(
             'local' => 'id',
             'foreign' => 'contact_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}