<?php

/**
 * BaseKeyword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $flag_id
 * @property string $name
 * @property text $description
 * @property integer $weight
 * @property Flag $Flag
 * @property Doctrine_Collection $EmailKeyword
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getFlagId()       Returns the current record's "flag_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method text                getDescription()  Returns the current record's "description" value
 * @method integer             getWeight()       Returns the current record's "weight" value
 * @method Flag                getFlag()         Returns the current record's "Flag" value
 * @method Doctrine_Collection getEmailKeyword() Returns the current record's "EmailKeyword" collection
 * @method Keyword             setId()           Sets the current record's "id" value
 * @method Keyword             setFlagId()       Sets the current record's "flag_id" value
 * @method Keyword             setName()         Sets the current record's "name" value
 * @method Keyword             setDescription()  Sets the current record's "description" value
 * @method Keyword             setWeight()       Sets the current record's "weight" value
 * @method Keyword             setFlag()         Sets the current record's "Flag" value
 * @method Keyword             setEmailKeyword() Sets the current record's "EmailKeyword" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKeyword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('keyword');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('flag_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('weight', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Flag', array(
             'local' => 'flag_id',
             'foreign' => 'id'));

        $this->hasMany('EmailKeyword', array(
             'local' => 'id',
             'foreign' => 'keyword_id'));
    }
}