<?php

/**
 * BaseEmailKeyword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $email_id
 * @property integer $keyword_id
 * @property Email $Email
 * @property Keyword $Keyword
 * 
 * @method integer      getEmailId()    Returns the current record's "email_id" value
 * @method integer      getKeywordId()  Returns the current record's "keyword_id" value
 * @method Email        getEmail()      Returns the current record's "Email" value
 * @method Keyword      getKeyword()    Returns the current record's "Keyword" value
 * @method EmailKeyword setEmailId()    Sets the current record's "email_id" value
 * @method EmailKeyword setKeywordId()  Sets the current record's "keyword_id" value
 * @method EmailKeyword setEmail()      Sets the current record's "Email" value
 * @method EmailKeyword setKeyword()    Sets the current record's "Keyword" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmailKeyword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('email_keyword');
        $this->hasColumn('email_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('keyword_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Email', array(
             'local' => 'email_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Keyword', array(
             'local' => 'keyword_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}