<?php

/**
 * BaseAuditLogger
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $module
 * @property string $action
 * @property integer $object_id
 * @property clob $params
 * @property sfGuardUser $User
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method integer     getUserId()    Returns the current record's "user_id" value
 * @method string      getModule()    Returns the current record's "module" value
 * @method string      getAction()    Returns the current record's "action" value
 * @method integer     getObjectId()  Returns the current record's "object_id" value
 * @method clob        getParams()    Returns the current record's "params" value
 * @method sfGuardUser getUser()      Returns the current record's "User" value
 * @method AuditLogger setId()        Sets the current record's "id" value
 * @method AuditLogger setUserId()    Sets the current record's "user_id" value
 * @method AuditLogger setModule()    Sets the current record's "module" value
 * @method AuditLogger setAction()    Sets the current record's "action" value
 * @method AuditLogger setObjectId()  Sets the current record's "object_id" value
 * @method AuditLogger setParams()    Sets the current record's "params" value
 * @method AuditLogger setUser()      Sets the current record's "User" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuditLogger extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('audit_logger');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('module', 'string', 96, array(
             'type' => 'string',
             'length' => 96,
             ));
        $this->hasColumn('action', 'string', 96, array(
             'type' => 'string',
             'length' => 96,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('params', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}