<?php

/**
 * BaseInmateContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $inmate_id
 * @property integer $contact_id
 * @property Inmate $Inmate
 * @property Contact $Contact
 * 
 * @method integer       getInmateId()   Returns the current record's "inmate_id" value
 * @method integer       getContactId()  Returns the current record's "contact_id" value
 * @method Inmate        getInmate()     Returns the current record's "Inmate" value
 * @method Contact       getContact()    Returns the current record's "Contact" value
 * @method InmateContact setInmateId()   Sets the current record's "inmate_id" value
 * @method InmateContact setContactId()  Sets the current record's "contact_id" value
 * @method InmateContact setInmate()     Sets the current record's "Inmate" value
 * @method InmateContact setContact()    Sets the current record's "Contact" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInmateContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inmate_contact');
        $this->hasColumn('inmate_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('contact_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Inmate', array(
             'local' => 'inmate_id',
             'foreign' => 'id'));

        $this->hasOne('Contact', array(
             'local' => 'contact_id',
             'foreign' => 'id'));
    }
}