<?php

/**
 * BaseOfficer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $badge_number
 * @property integer $user_id
 * @property sfGuardUser $User
 * 
 * @method integer     getId()           Returns the current record's "id" value
 * @method string      getBadgeNumber()  Returns the current record's "badge_number" value
 * @method integer     getUserId()       Returns the current record's "user_id" value
 * @method sfGuardUser getUser()         Returns the current record's "User" value
 * @method Officer     setId()           Sets the current record's "id" value
 * @method Officer     setBadgeNumber()  Sets the current record's "badge_number" value
 * @method Officer     setUserId()       Sets the current record's "user_id" value
 * @method Officer     setUser()         Sets the current record's "User" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOfficer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('officer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('badge_number', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}