<?php

/**
 * BaseInmate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $email_number
 * @property integer $jail_number
 * @property double $balance
 * @property boolean $contacts_approvable
 * @property boolean $emails_approvable
 * @property sfGuardUser $User
 * @property Doctrine_Collection $InmateContact
 * @property Doctrine_Collection $Email
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getUserId()              Returns the current record's "user_id" value
 * @method integer             getEmailNumber()         Returns the current record's "email_number" value
 * @method integer             getJailNumber()          Returns the current record's "jail_number" value
 * @method double              getBalance()             Returns the current record's "balance" value
 * @method boolean             getContactsApprovable()  Returns the current record's "contacts_approvable" value
 * @method boolean             getEmailsApprovable()    Returns the current record's "emails_approvable" value
 * @method sfGuardUser         getUser()                Returns the current record's "User" value
 * @method Doctrine_Collection getInmateContact()       Returns the current record's "InmateContact" collection
 * @method Doctrine_Collection getEmail()               Returns the current record's "Email" collection
 * @method Inmate              setId()                  Sets the current record's "id" value
 * @method Inmate              setUserId()              Sets the current record's "user_id" value
 * @method Inmate              setEmailNumber()         Sets the current record's "email_number" value
 * @method Inmate              setJailNumber()          Sets the current record's "jail_number" value
 * @method Inmate              setBalance()             Sets the current record's "balance" value
 * @method Inmate              setContactsApprovable()  Sets the current record's "contacts_approvable" value
 * @method Inmate              setEmailsApprovable()    Sets the current record's "emails_approvable" value
 * @method Inmate              setUser()                Sets the current record's "User" value
 * @method Inmate              setInmateContact()       Sets the current record's "InmateContact" collection
 * @method Inmate              setEmail()               Sets the current record's "Email" collection
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInmate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('inmate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('jail_number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('balance', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('contacts_approvable', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('emails_approvable', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('InmateContact', array(
             'local' => 'id',
             'foreign' => 'inmate_id'));

        $this->hasMany('Email', array(
             'local' => 'id',
             'foreign' => 'inmate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}