<?php

/**
 * BaseConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property text $description
 * @property string $config_key
 * @property text $config_value
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method string        getTitle()        Returns the current record's "title" value
 * @method text          getDescription()  Returns the current record's "description" value
 * @method string        getConfigKey()    Returns the current record's "config_key" value
 * @method text          getConfigValue()  Returns the current record's "config_value" value
 * @method Configuration setId()           Sets the current record's "id" value
 * @method Configuration setTitle()        Sets the current record's "title" value
 * @method Configuration setDescription()  Sets the current record's "description" value
 * @method Configuration setConfigKey()    Sets the current record's "config_key" value
 * @method Configuration setConfigValue()  Sets the current record's "config_value" value
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('configuration');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('config_key', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('config_value', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}