config:
  class: sfDoctrineRouteCollection
  options:
    model:                Config
    module:               config
    prefix_path:          /config
    column:               id
    with_wildcard_routes: true

configuration:
  class: sfDoctrineRouteCollection
  options:
    model:                Configuration
    module:               configuration
    prefix_path:          /configuration
    column:               id
    with_wildcard_routes: true

audit_logger_audit_log:
  class: sfDoctrineRouteCollection
  options:
    model:                AuditLogger
    module:               audit_log
    prefix_path:          /audit_log
    column:               id
    with_wildcard_routes: true

officer:
  class: sfDoctrineRouteCollection
  options:
    model:                Officer
    module:               officer
    prefix_path:          /officer
    column:               id
    with_wildcard_routes: true

keyword:
  class: sfDoctrineRouteCollection
  options:
    model:                Keyword
    module:               keyword
    prefix_path:          /keyword
    column:               id
    with_wildcard_routes: true

flag:
  class: sfDoctrineRouteCollection
  options:
    model:                Flag
    module:               flag
    prefix_path:          /flag
    column:               id
    with_wildcard_routes: true

email_outgoing:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailOutgoing
    module:               email_outgoing
    prefix_path:          /email_outgoing
    column:               id
    with_wildcard_routes: true

email_incoming:
  class: sfDoctrineRouteCollection
  options:
    model:                EmailIncoming
    module:               email_incoming
    prefix_path:          /email_incoming
    column:               id
    with_wildcard_routes: true

email:
  class: sfDoctrineRouteCollection
  options:
    model:                Email
    module:               email
    prefix_path:          /email
    column:               id
    with_wildcard_routes: true

contact:
  class: sfDoctrineRouteCollection
  options:
    model:                Contact
    module:               contact
    prefix_path:          /contact
    column:               id
    with_wildcard_routes: true

inmate_inmate:
  class: sfDoctrineRouteCollection
  options:
    model:                Inmate
    module:               inmate
    prefix_path:          /inmate
    column:               id
    with_wildcard_routes: true

inmate:
  class: sfDoctrineRouteCollection
  options:
    model:                Inmate
    module:               Inmate
    prefix_path:          /Inmate
    column:               id
    with_wildcard_routes: true

audit_logger:
  class: sfDoctrineRouteCollection
  options:
    model:                AuditLogger
    module:               audit_logger
    prefix_path:          /audit_logger
    column:               id
    with_wildcard_routes: true


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: inmate, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_signin:
  url: /login
  param:
    module: sfGuardAuth
    action: signin

sf_guard_signout:
  url: /logout
  param:
    module: sfGuardAuth
    action: signout

sf_guard_forgot_password:
  url: /guard/forgot_password
  param:
    module: sfGuardForgotPassword

sf_guard_user:
  url: /guard/user
  param:
    module: sfGuardUser

sf_guard_group:
  url: /guard/group
  param:
    module: sfGuardGroup

sf_guard_permission:
  url: /guard/permission
  param:
    module: sfGuardPermission

