generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EmailOutgoing
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          email_outgoing
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [inmate,scanned,sufficient,sent]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
