<?php

/**
 * AuditLoggerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuditLoggerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuditLoggerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuditLogger');
    }
}