<?php

/**
 * Config
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Config extends BaseConfig
{

    public static function getVal($config_key) {

        $config = Doctrine_Query::create()
        ->from('Config c')
        ->where('c.config_key = ?',$config_key)
        ->fetchOne();
 
        if($config)
            return $config->config_value;
    }
}
