<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }

    public static function getByEmailAddress($email_address) {

        $contact = Doctrine_Query::create()
        ->from('Contact c, c.InmateContact ic')
        ->where('c.email_address = ?',$email_address)
        ->fetchArray();

        return end($contact);
    }
}
