<?php

/**
 * Email
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Email extends BaseEmail
{

    public function getWhenCreated($format = 'M d, Y h:i a') {

        return $this->getDateTimeObject('created_at')->format($format);
    }

    public static function getByScan($scanned) {

        return Doctrine_Query::create() 
        ->from('Email e')
        ->where('e.scanned = ?',$scanned)
        ->execute();
    }

    public static function calculatePendingCharges() {
        $price = sfConfig::get('sf_send_email_price');

        $unsent_emails = Doctrine_Query::create() 
        ->select('eo.id')
        ->from('EmailOutgoing eo, eo.Email e')
        ->where('e.inmate_id = ?', InmateTable::loggedIn()->getId())
        ->andWhere('eo.sent = ?',0)
        ->fetchArray();

        return number_format(round(count($unsent_emails) * $price,2),2);
    }
}
