<?php

/**
 * EmailOutgoing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    projectname
 * @subpackage model
 * @author     Joseph Persie
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EmailOutgoing extends BaseEmailOutgoing
{

    public function getRecipient() {

        $contact = trim($this->getEmail()->getContact()->__toString());

        if(!empty($contact)){
            $recipient = $this->getEmail()->getContact();
        }
        else {
            $recipient = $this->getRecipientEmail();
        } 

        return $recipient;
    }

    public function getInmate() {
        
        return $this->getEmail()->getInmate();
    }

    public function getApproved() {
        return $this->getEmail()->getApproved();
    }

    public function getDisapproved() {
        return $this->getEmail()->getDisapproved();
    }

    public function getSufficient() {
        return $this->getEmail()->getSufficient();
    }

    public static function getQueued() {

        return Doctrine_Query::create()
        ->from('EmailOutgoing eo, eo.Email e')
        ->where('eo.sent = ?',false)
        ->andWhere('eo.scanned = ?',false)
        ->execute();

    }

    public static function getById($id) {

        return Doctrine_Query::create()
        ->from('EmailOutgoing eo, eo.Email e')
        ->where('eo.id = ?',$id)
        ->fetchOne();
    }

    public static function getAuthorizedEmailById($id) {
    
        return Doctrine_Query::create()
        ->from('EmailOutgoing eo, eo.Email e')
        ->where('eo.id = ?',$id)
        ->andWhere('e.inmate_id = ?',InmateTable::loggedIn()->getId())
        ->fetchOne();
    }


    //this will not retrieve cancelled emails
    public function getByScanAndCount($scanned,$count=false) {

        $q = Doctrine_Query::create()
        ->from('EmailOutgoing eo, eo.Email e')
        ->where('e.approved = ?',$scanned)
        ->andWhere('e.disapproved = ?',$scanned)
        ->andWhere('eo.cancelled = ?',false);

        if($count) $q = $q->limit($count);        

        return $q->execute();
    }
}
