<?php

/**
 * EmailIncomingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailIncomingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailIncomingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailIncoming');
    }
}