<?php

/**
 * EmailOutgoingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailOutgoingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailOutgoingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailOutgoing');
    }
}