<?php

/**
 * FlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Flag');
    }
}