<?php

/**
 * InmateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InmateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InmateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inmate');
    }
}