<?php

/**
 * InmateContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InmateContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InmateContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InmateContact');
    }
}