<?php

/**
 * InmateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InmateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InmateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Inmate');
    }

    public static function getLoggedIn() {

      $q = Doctrine_Query::create()
      ->from('Inmate i')
      ->where('i.user_id = ?',myUser::getLoggedIn()->getId());

      return $q;
    }

    public static function loggedIn() {
      return InmateTable::getLoggedIn()->fetchOne();
    }

    public function getByUserId($user_id) {

        return Doctrine_Query::create()
               ->from('Inmate i')
               ->where('i.user_id = ?',$user_id)
               ->limit(1)
               ->fetchOne();
    }

    public static function hasSufficientFundsFor($config_key) {

        $calc = (float)InmateTable::getCurrentBalance() - Config::getVal($config_key);

        return ($calc>=0);
    }

    public static function getCurrentBalance() {

        $calc =  self::loggedIn()->getBalance() - Inmate::calculatePendingChargesByLoggedIn();

        return number_format(round($calc,2),2);
    }
}
