generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AuditLogger
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          audit_logger
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Audit Log Management
        display: [User, module, object_id]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
