<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('sfGuardUser');
    }

    public function getPatients() {
        return Doctrine_Core::getTable('Patient')->findAll();
    }

    public function getTechnologists() {
        return $this->getWhereGroupLike("%Technologist%");
    }

    public function getReferringmds() {
        return $this->getWhereGroupLike("%Referring%");
    }

    public function getOrderingmds() {
        return $this->getWhereGroupLike("%Ordering%");
    }

    public function getReadingmds() {
        return $this->getWhereGroupLike("%Reading%");
    }

    public function getWhereGroupLike($like) {
        return Doctrine_Query::create()
               ->from('sfGuardUser u, u.GroupUserLocations gul, gul.Group g')
               ->where('g.name LIKE ?',$like)
               ->execute();
    }

    public function getByGroupAndLocation($group,$location_id) {

        if($group == "Patient") {
            return Doctrine_Core::getTable('Patient')->searchWith(array('location_id'=>$location_id));
        }
        else {
            return Doctrine_Query::create()
                   ->from('GroupUserLocations gul, gul.User, gul.Group g')
                   ->where('g.name LIKE ?',$group)
                   ->andWhere('gul.location_id = ?',$location_id)
                   ->execute();
        }
    }
}
