# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~
security:  ~

#insert your own filters here
auth_redirect:
  class: authRedirectFilter
  param:
    moduleRoot: 'officers'

cache:     ~
execution: ~
