# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    app_root_path:          /
    app_root_script:        officers.php

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false
    app_root_path:          /
    app_root_script:        officers_dev.php

sandbox:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
    app_root_path:          /
    app_root_script:        officers_sandbox.php

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            b06929491db483ab7a52abdf13716a5cf03d2eee

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:        [default, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardForgotPassword]

  .actions:
    login_module: sfGuardAuth
    login_action: signin

    secure_module: sfGuardAuth
    secure_action: secure

