# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    app_root_path:          /clients/inmateemail/web/
    app_root_script:        inmates.php

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false
    app_root_path:          /clients/inmateemail/web/
    app_root_script:        inmates_dev.php

sandbox:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
    app_root_path:          /
    app_root_script:        inmates_sandbox.php

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            1f58e730cd15c7d10b564e19e87db88d3c077c3c

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:        [default, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardForgotPassword]
    # Email pricing
    send_email_price:              1.25
    recieve_email_price:           1.25

  .actions:
    login_module: sfGuardAuth
    login_action: signin

    secure_module: sfGuardAuth
    secure_action: secure

