generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EmailIncoming
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          email_incoming
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [inmate,sufficient,scanned,sender]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
